services:
  server-dev:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
      target: development
    container_name: monorepo-dev-server
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/server/node_modules
    env_file:
      - apps/server/.env
    ports:
      - 3210:3210
    command: >
      pnpm --filter @repo/server dev
