services:
  server-dev:
    build:
      context: .
      # dockerfile: apps/server/Dockerfile.dev
      dockerfile: apps/server/Dockerfile
      target: development
    container_name: monorepo-dev-server
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/server/node_modules
      # - /app/packages/database/node_modules
      # - /app/packages/types/node_modules
      # - /app/packages/utils/node_modules
    env_file:
      - .env
      - apps/server/.env
    ports:
      - 3210:3210
    environment:
      - TSX_LOADER_FALLBACK=1
      - CHOKIDAR_USEPOLLING=1
      - CHOKIDAR_INTERVAL=100
    command: >
      pnpm --filter @repo/server dev
