export const RESPONSE_STATUSES = {
  SUCCESS: 'SUCCESS',
  CREATED: 'CREATED',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  SERVER_ERROR: 'SERVER_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  SERVER_ALIVE: 'SERVER_ALIVE',
  DB_ALIVE: 'DB_ALIVE',
} as const;

export const RESPONSE_CODES = {
  200: 200,
  201: 201,
  400: 400,
  401: 401,
  403: 403,
  404: 404,
  500: 500,
  501: 501,
  2000: 2000,
  5000: 5000,
} as const;

export const RESPONSE_CODES_STATUSES = {
  [RESPONSE_CODES[200]]: RESPONSE_STATUSES.SUCCESS,
  [RESPONSE_CODES[201]]: RESPONSE_STATUSES.CREATED,
  [RESPONSE_CODES[400]]: RESPONSE_STATUSES.BAD_REQUEST,
  [RESPONSE_CODES[401]]: RESPONSE_STATUSES.UNAUTHORIZED,
  [RESPONSE_CODES[403]]: RESPONSE_STATUSES.FORBIDDEN,
  [RESPONSE_CODES[404]]: RESPONSE_STATUSES.NOT_FOUND,
  [RESPONSE_CODES[500]]: RESPONSE_STATUSES.SERVER_ERROR,
  [RESPONSE_CODES[501]]: RESPONSE_STATUSES.NOT_IMPLEMENTED,
  [RESPONSE_CODES[2000]]: RESPONSE_STATUSES.SERVER_ALIVE,
  [RESPONSE_CODES[5000]]: RESPONSE_STATUSES.DB_ALIVE,
} as const;

export const RESPONSE_STATUSES_MESSAGES = {
  [RESPONSE_STATUSES.SUCCESS]: 'The request succeeded.',
  [RESPONSE_STATUSES.CREATED]: 'The request succeeded, and a new resource was created as a result.',
  [RESPONSE_STATUSES.BAD_REQUEST]: 'The server cannot process the request.',
  [RESPONSE_STATUSES.UNAUTHORIZED]: 'Unauthenticated',
  [RESPONSE_STATUSES.FORBIDDEN]: 'The client does not have access rights to the content.',
  [RESPONSE_STATUSES.NOT_FOUND]: 'The server cannot find the requested resource.',
  [RESPONSE_STATUSES.SERVER_ERROR]: 'Internal server error.',
  [RESPONSE_STATUSES.NOT_IMPLEMENTED]: 'The request method is not supported by the server.',
  [RESPONSE_STATUSES.SERVER_ALIVE]: 'The server is ready to process requests.',
  [RESPONSE_STATUSES.DB_ALIVE]: 'The database is ready to process data.',
} as const;
